'use client';

import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { AlertTriangle, CheckCircle2, Send } from 'lucide-react';

import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import type { BillingRun, Invoice } from '@/lib/api';
import { issueBillingRun } from '@/lib/billing-actions';

const formatIdr = (n: number) => `Rp ${n.toLocaleString('id-ID')}`;

const periodLabel = (period: string) => {
  const [y, m] = period.split('-').map(Number);
  if (!y || !m) return period;
  return new Date(Date.UTC(y, m - 1, 1)).toLocaleDateString('id-ID', {
    month: 'long',
    year: 'numeric',
  });
};

/**
 * Review a drafted month, then issue it (doc 14 §1.6).
 *
 * The whole reason DRAFT exists: a month of invoices is generated by a cron at
 * three in the morning, and somebody looks at it before any of it reaches a
 * family. Issuing is one click, so this screen has to make the consequences of
 * that click legible first, how many families, how much money, and any invoice
 * that looks wrong.
 */
export function BillingRunReview({ runs, drafts }: { runs: BillingRun[]; drafts: Invoice[] }) {
  const router = useRouter();
  const [confirming, setConfirming] = useState<BillingRun | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  /** One key per opened confirmation, not per click. */
  const [idemKey, setIdemKey] = useState('');

  const open = (run: BillingRun) => {
    setConfirming(run);
    setError(null);
    setIdemKey(crypto.randomUUID());
  };

  const issue = async () => {
    if (!confirming) return;
    setBusy(true);
    const result = await issueBillingRun(confirming.id, idemKey);
    setBusy(false);

    if (!result.ok) {
      setError(result.error ?? 'Gagal menerbitkan.');
      return;
    }
    setConfirming(null);
    router.refresh();
  };

  const draftRun = runs.find((r) => r.status === 'DRAFT');
  const draftsForRun = draftRun ? drafts.filter((d) => d.status === 'DRAFT') : [];

  /**
   * Anything a human should look at before a month goes out.
   *
   * A zero-amount invoice means a programme with no price, and a family
   * receiving a bill for Rp0 will either ignore it or ring up confused. Better
   * to surface it here than to find out from them.
   */
  const suspicious = draftsForRun.filter((d) => d.amount <= 0);

  return (
    <div className="space-y-8">
      {draftRun ? (
        <section className="border-navy/20 rounded-2xl border bg-white p-6">
          <div className="flex flex-wrap items-start justify-between gap-4">
            <div>
              <span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-semibold text-amber-700">
                Draf, belum dikirim
              </span>
              <h2 className="mt-3 text-lg font-semibold tracking-tight text-neutral-900">
                Tagihan {periodLabel(draftRun.period)}
              </h2>
              <p className="mt-1 text-sm text-neutral-500">
                {draftRun.invoiceCount} tagihan · total {formatIdr(draftRun.totalAmount)}
              </p>
            </div>

            <button
              type="button"
              onClick={() => open(draftRun)}
              disabled={draftRun.invoiceCount === 0}
              className="bg-navy hover:bg-navy-dark flex shrink-0 items-center gap-2 rounded-full px-6 py-3 text-sm font-semibold text-white transition-colors disabled:opacity-60"
            >
              <Send className="h-4 w-4" />
              Terbitkan Semua
            </button>
          </div>

          {suspicious.length > 0 && (
            <div className="border-maroon/30 bg-maroon-light/40 mt-5 flex items-start gap-2 rounded-xl border p-4">
              <AlertTriangle className="text-maroon mt-0.5 h-4 w-4 shrink-0" />
              <p className="text-xs text-neutral-700">
                {suspicious.length} tagihan bernilai Rp0, biasanya karena harga program belum
                diatur. Periksa dulu sebelum diterbitkan.
              </p>
            </div>
          )}

          {/*
            The count comes from the run itself; the list is capped by the API.
            Saying so beats a list that silently stops short of what will be
            issued. Finance would review 100 invoices and send 140.
          */}
          {draftsForRun.length < draftRun.invoiceCount && (
            <p className="mt-4 rounded-xl bg-neutral-50/70 p-3 text-xs text-neutral-500">
              Menampilkan {draftsForRun.length} dari {draftRun.invoiceCount} tagihan. Sisanya tetap
              ikut diterbitkan.
            </p>
          )}

          {draftsForRun.length === 0 ? (
            <p className="mt-5 rounded-xl border border-dashed border-neutral-300 px-4 py-8 text-center text-sm text-neutral-400">
              Belum ada tagihan di draf ini. Semua siswa aktif mungkin sudah ditagih untuk periode
              tersebut.
            </p>
          ) : (
            <ul className="mt-5 divide-y divide-neutral-100">
              {draftsForRun.map((d) => (
                <li key={d.id} className="flex items-center justify-between gap-4 py-3">
                  <div className="min-w-0">
                    <p className="truncate text-sm font-medium text-neutral-900">{d.studentName}</p>
                    <p className="truncate font-mono text-xs text-neutral-400">{d.number}</p>
                  </div>
                  <p
                    className={`shrink-0 text-sm font-semibold ${
                      d.amount <= 0 ? 'text-maroon' : 'text-neutral-900'
                    }`}
                  >
                    {formatIdr(d.amount)}
                  </p>
                </li>
              ))}
            </ul>
          )}
        </section>
      ) : (
        <section className="rounded-2xl border border-dashed border-neutral-300 px-6 py-10 text-center">
          <p className="text-sm text-neutral-500">Tidak ada draf tagihan yang menunggu.</p>
          <p className="mt-1 text-xs text-neutral-400">
            Sistem membuat draf tagihan bulan berikutnya otomatis setiap tanggal 25.
          </p>
        </section>
      )}

      {/* History, what was issued, when, and by whom. */}
      {runs.some((r) => r.status === 'ISSUED') && (
        <section>
          <h2 className="text-base font-semibold tracking-tight text-neutral-900">
            Riwayat Penerbitan
          </h2>
          <ul className="mt-4 space-y-2">
            {runs
              .filter((r) => r.status === 'ISSUED')
              .map((r) => (
                <li
                  key={r.id}
                  className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-neutral-200/70 bg-white px-5 py-3"
                >
                  <div className="min-w-0">
                    <p className="text-sm font-medium text-neutral-900">{periodLabel(r.period)}</p>
                    <p className="text-xs text-neutral-400">
                      {r.invoiceCount} tagihan · {formatIdr(r.totalAmount)}
                      {r.issuedByName && ` · diterbitkan ${r.issuedByName}`}
                    </p>
                  </div>
                  <CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-600" />
                </li>
              ))}
          </ul>
        </section>
      )}

      <Dialog open={!!confirming} onOpenChange={(o) => !o && setConfirming(null)}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>
              Terbitkan tagihan {confirming && periodLabel(confirming.period)}?
            </DialogTitle>
          </DialogHeader>

          <div className="space-y-4">
            {/*
              Spell out what happens, because it is not undoable: the invoices
              become real and every family is emailed. "Are you sure?" without
              the consequences is a dialog people learn to click through.
            */}
            <div className="rounded-xl bg-neutral-50/70 p-4 text-sm text-neutral-700">
              <p>
                <strong>{confirming?.invoiceCount} tagihan</strong> senilai{' '}
                <strong>{confirming && formatIdr(confirming.totalAmount)}</strong> akan diterbitkan.
              </p>
              <p className="mt-2 text-xs text-neutral-500">
                Setiap keluarga langsung menerima email berisi tagihannya, dan tagihan muncul di
                portal orang tua. Tindakan ini tidak bisa dibatalkan, tagihan yang salah harus
                dibatalkan satu per satu.
              </p>
            </div>

            {error && <p className="text-maroon text-xs">{error}</p>}

            <div className="flex gap-2">
              <button
                type="button"
                onClick={issue}
                disabled={busy}
                className="bg-navy hover:bg-navy-dark flex flex-1 items-center justify-center gap-2 rounded-full py-2.5 text-sm font-semibold text-white transition-colors disabled:opacity-60"
              >
                <Send className="h-4 w-4" />
                {busy ? 'Menerbitkan…' : 'Ya, terbitkan'}
              </button>
              <button
                type="button"
                onClick={() => setConfirming(null)}
                className="rounded-full border border-neutral-200 px-5 py-2.5 text-sm font-semibold text-neutral-600 transition-colors hover:bg-neutral-50"
              >
                Batal
              </button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
